version: "3.8"
services:
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  api:
    build: ./backend
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: dnd
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  mongo_data:
